### PR TITLE
Barebones implementation of spellchecker and suggested search

### PR DESCRIPTION
**Pull request by PushkarBettadpur**
@harsh376

### CODE REVIEW

**Review by harsh376 — COMMENTED** [review]
add `enchant` to `requirements.txt`

`source venv/bin/activate`
`pip install pyenchant`
`pip freeze > requirements.txt`

**Review by harsh376 — COMMENTED** [review]
functionality-wise is good. need to fix css though

**Comment by harsh376** [comment]
fixes #11

**Comment by PushkarBettadpur** [comment]
@harsh376 done

**Review by harsh376 — APPROVED** [review]
Reviewed. Good to merge 💯

**Comment by PushkarBettadpur** [comment]
@harsh376 so added an autopredict feature. Needs much work. I'm not sure why only the first link is clicking. 
Let me know if you're able to get it. And i've noticed it fails in some cases, but overall, it seems kinda cool.

AND I ACCIDENTALLY MESSED UP requirements.txt I think. For some reason my pip freeze > requirements.txt didn't work as expected. You'll need to pip install autocomplete

**Pull request merged**
